export const ADD_BUCKET_REQUEST='ADD_BUCKET_REQUEST';
export const ADD_BUCKET_SUCCESS='ADD_BUCKET_SUCCESS';
export const ADD_BUCKET_FAIL='ADD_BUCKET_FAIL';

export const GET_BUCKET_REQUEST='GET_BUCKET_REQUEST';
export const GET_BUCKET_SUCCESS='GET_BUCKET_SUCCESS';
export const GET_BUCKET_FAIL='GET_BUCKET_FAIL';

export const DELETE_BUCKET_REQUEST='DELETE_BUCKET_REQUEST';
export const DELETE_BUCKET_SUCCESS='DELETE_BUCKET_SUCCESS';
export const DELETE_BUCKET_FAIL='DELETE_BUCKET_FAIL';

export const ADD_TODO_REQUEST='ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL='ADD_TODO_FAIL';

export const GET_TODO_REQUEST='GET_TODO_REQUEST';
export const GET_TODO_SUCCESS='GET_TODO_SUCCESS';
export const GET_TODO_FAIL='GET_TODO_FAIL';

export const DELETE_TODO_REQUEST='DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS='DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL='DELETE_TODO_FAIL';

export const UPDATE_TODO_REQUEST='UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS='UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAIL='UPDATE_TODO_FAIL';

export const UPDATE_TODO_STATUS_REQUEST='UPDATE_TODO_STATUS_REQUEST';
export const UPDATE_TODO_STATUS_SUCCESS='UPDATE_TODO_STATUS_SUCCESS';
export const UPDATE_TODO_STATUS_FAIL='UPDATE_TODO_STATUS_FAIL';
